export default [
	{
		title: "Portfólio",
		imgSrc: "/img/project/fundo_q.gif",
		alt: "ceu estrado",
		tags: "React, Tailwind, Framer Motion, TypeScript, i18n",
		id: "React, Tailwind, Framer Motion, TypeScript, i18n",
		siteLink: "https://portfolio-moniquead.vercel.app/",
		githubLink: "https://github.com/Monique-Duarte/Portfolio_2025.git",
	},	
	{
		title: "Cópia Disney +",
		imgSrc: "/img/project/disney.png",
		alt: "disney",
		tags: "Css, JavaScripts, Gulp",
		id: "Css, JavaScripts, Gulp",
		siteLink: "https://clone-disney-plus-nine-liard.vercel.app/",
		githubLink: "https://github.com/Monique-Duarte/Clone_DisneyPlus",
	}, 	
	{
		title: "Lista Telefonica",
		imgSrc: "/img/project/lista.png",
		alt: "Lista Telefonica",
		tags: "AngularJS, CSS, Bootstrap",
		id: "AngularJS, CSS, Bootstrap",
		siteLink: "https://lista-telefonica-omega.vercel.app/",
		githubLink: "https://lista-telefonica-mu.vercel.app/",
	},
	{
		title: "Hema Toma",
		imgSrc: "/img/project/game.jpg",
		alt: "controle de video game",
		tags: "React, bootstrap, TypeScript, CSS",
		id: "React, bootstrap, TypeScript, CSS",
		siteLink: "https://game-hema-toma.vercel.app/",
		githubLink: "https://github.com/Monique-Duarte/Game-Hema-Toma.git",
	},
	{
		title: "Restaurante",
		imgSrc: "/img/project/restaurante.jpg",
		alt: "restaurante",
		tags: "JavaScript, HTML, CSS, Bootstrap",
		id: "JavaScript, HTML, CSS, Bootstrap",
		siteLink: "https://page-restaurante-alpha.vercel.app/",
		githubLink: "https://github.com/Monique-Duarte/Projeto-3-Page-Restaurante.git",
	},
	{
		title: "Cronômetro",
		imgSrc: "/img/project/cronometro.jpg",
		alt: "Cronômetro",
		tags: "TypeScript, React, CSS, HTML, SCSS",
		id: "TypeScript, React, CSS, HTML, SCSS",
		siteLink: "https://cronometro-zeta-ebon.vercel.app/",
		githubLink: "https://github.com/Monique-Duarte/Tarefas-Cronometro",
	},
	{
		title: "Allfood",
		imgSrc: "/img/project/allfood.jpg",
		alt: "Site de comida",
		tags: "React, TypeScript, CSS, HTML, API, Python, Docker, Node.js",
		id: "React, TypeScript, CSS, HTML, API, Python, Docker, Node.js",
		siteLink: " ",
		githubLink: "https://github.com/Monique-Duarte/AllFood",
	},
	{
		title: "Sorteador",
		imgSrc: "/img/project/sorteador.jpg",
		alt: "Sorteador numérico",
		tags: "Grunt, JavaScript, HTML, CSS",
		id: "Grunt, JavaScript, HTML, CSS",
		siteLink: "https://sorteador-ten-eosin.vercel.app/",
		githubLink: "https://github.com/Monique-Duarte/Sorteador_Grunt",
	},
	{
		title: "Spotify",
		imgSrc: "/img/project/spotify.jpg",
		alt: "Cópia funcional Spotify",
		tags: "JavaScript, HTML, CSS",
		id: "JavaScript, HTML, CSS",
		siteLink: " ",
		githubLink: "https://github.com/Monique-Duarte/Projeto-Hashtag-Spotify",
	},
	{
		title: "Portfólio Less",
		imgSrc: "/img/project/portless.png",
		alt: "Miniatura do site",
		tags: "HTML, CSS, Less, Javascript",
		id: "HTML, CSS, Less, Javascript",
		siteLink: "https://portfolio-less-seven.vercel.app/",
		githubLink: "https://github.com/Monique-Duarte/Portfolio-Less.git",
	},
	{
		title: "Blog de Noticias",
		imgSrc: "/img/project/image.png",
		alt: "Jornal",
		tags: "HTML, CSS",
		id: "HTML, CSS",
		siteLink: "https://projeto-blog-noticias.vercel.app/",
		githubLink: "https://github.com/Monique-Duarte/Projeto-blog-noticias.git",
	},
	{
		title: "Neko Shop",
		imgSrc: "/img/project/logo.png",
		alt: "Logo gato laranja",
		tags: "HTML, CSS",
		id: "HTML, CSS",
		siteLink: "https://neko-shop.vercel.app/",
		githubLink: "https://github.com/Monique-Duarte/Neko-Shop-origin.git",
	},
	{
		title: "Game Shop",
		imgSrc: "/img/project/gif_mario2.gif",
		alt: "Dois controles de video game",
		tags: "HTML, CSS",
		id: "HTML, CSS",
		siteLink: "https://site-game-shop-ten-coral.vercel.app/",
		githubLink: "https://github.com/Monique-Duarte/Site-Game-Shop.git",
	},
	{
		title: "Portal de Notícias",
		imgSrc: "/img/project/image.png",
		alt: "Jornal",
		tags: "HTML, CSS",
		id: "HTML, CSS",
		siteLink: "https://meu-portal-mu.vercel.app/",
		githubLink: "https://github.com/Monique-Duarte/Portal-de-Noticias.git",
	},
	{
		title: "Formulário",
		imgSrc: "/img/project/form.png",
		alt: "Prancheta",
		tags: "HTML, CSS, JavaScript",
		id: "HTML, CSS, JavaScript",
		siteLink: "https://formulario-js-plum.vercel.app/",
		githubLink: "https://github.com/Monique-Duarte/Formulario_JS.git",
	},
	{
		title: "Galeria de fotos",
		imgSrc: "/img/project/camera.png",
		alt: "Camera",
		tags: "HTML, CSS",
		id: "HTML, CSS",
		siteLink: "https://galeria-de-fotos-cyan.vercel.app/",
		githubLink: "https://github.com/Monique-Duarte/Galeria-de-Fotos.git",
	},
	{
		title: "Ebac Motors",
		imgSrc: "/img/project/carro.svg",
		alt: "Carro",
		tags: "HTML, CSS",
		id: "HTML, CSS",
		siteLink: "https://ebac-motors-six-alpha.vercel.app/",
		githubLink: "https://github.com/Monique-Duarte/Ebac-Motors.git",
	},
	{
		title: "Anuncio de venda",
		imgSrc: "/img/project/994737.png",
		alt: "Carrinho de compras",
		tags: "HTML, CSS",
		id: "HTML, CSS",
		siteLink: "https://anuncio-jquery.vercel.app/",
		githubLink: "https://github.com/Monique-Duarte/formulario-plugs-jquery.git",
	},
	{
		title: "Portal News",
		imgSrc: "/img/project/image.png",
		alt: "Jornal",
		tags: "HTML, CSS",
		id: "HTML, CSS",
		siteLink: "https://portal-de-noticias-grid.vercel.app/",
		githubLink: "https://github.com/Monique-Duarte/Ebac_News.git",
	},
	{
		title: "Agenda",
		imgSrc: "/img/project/pngwing.com.png",
		alt: "Logo telefone",
		tags: "HTML, CSS",
		id: "HTML, CSS",
		siteLink: "https://projeto-agendaonline.vercel.app/",
		githubLink: "https://github.com/Monique-Duarte/Projeto_Agenda.git",
	},
	{
		title: "Sistema de médias",
		imgSrc: "/img/project/calculadora.png",
		alt: "Calculadora",
		tags: "HTML, CSS",
		id: "HTML, CSS",
		siteLink: "https://monique-projeto-calculadora-medias.vercel.app/",
		githubLink: "https://github.com/Monique-Duarte/Projeto_Calculadora_Medias.git",
	},
	{
		title: "Lista de tarefas",
		imgSrc: "/img/project/form.png",
		alt: "formulário",
		tags: "HTML, CSS",
		id: "HTML, CSS",
		siteLink: "https://lista-de-tarefas-jquery-opal.vercel.app/",
		githubLink: "https://github.com/Monique-Duarte/Lista-de-tarefas_jquery.git",
	},
];