export default [
    {
    title: "GitHub - Portfólio",
    imgSrc: "/img/project/fundo_q.gif",
    alt: "logo de gato",
    tags: "#React #JS #Bootstrap",
    siteLink: "https://portfolio-moniquead.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Portfolio_2025.git",
    },
    {
    title: "Site - Hema Toma",
    imgSrc: "/img/project/game.jpg",
    alt: "controle de video game",
    tags: "#JS #Bootstrap",
    siteLink: "https://game-hema-toma.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Game-Hema-Toma.git",
    },
    {
    title: "Site - Restaurante",
    imgSrc: "/img/project/restaurante.jpg",
    alt: "restaurante",
    tags: "#JS #Bootstrap #Sass",
    siteLink: "https://page-restaurante-alpha.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Projeto-3-Page-Restaurante.git",
    },
    {
    title: "Portfólio Less",
    imgSrc: "/img/project/portless.png",
    alt: "Miniatura do site",
    tags: "#JS #Jquery #Less",
    siteLink: "https://portfolio-less-seven.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Portfolio-Less.git",
    },
    {
    title: "Blog de Noticias",
    imgSrc: "/img/project/image.png",
    alt: "Jornal",
    tags: "#JS #Bootstrap",
    siteLink: "https://projeto-blog-noticias.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Projeto-blog-noticias.git",
    },
    {
    title: "Neko Shop",
    imgSrc: "/img/project/logo.png",
    alt: "Logo gato laranja",
    tags: "#JS #Bootstrap",
    siteLink: "https://neko-shop.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Neko-Shop-origin.git",
    },
    {
    title: "Game Shop",
    imgSrc: "/img/project/gif_mario2.gif",
    alt: "Dois controles de video game",
    tags: "#JS #Bootstrap",
    siteLink: "https://site-game-shop-ten-coral.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Site-Game-Shop.git",
    },
    {
    title: "Portal de Notícias",
    imgSrc: "/img/project/image.png",
    alt: "Jornal",
    tags: "#JS #Bootstrap",
    siteLink: "https://meu-portal-mu.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Portal-de-Noticias.git",
    },
    {
    title: "Formulário",
    imgSrc: "/img/project/form.png",
    alt: "Prancheta",
    tags: "#JS #Bootstrap",
    siteLink: "https://formulario-js-plum.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Formulario_JS.git",
    },
    {
    title: "Galeria de fotos",
    imgSrc: "/img/project/camera.png",
    alt: "Camera",
    tags: "#JS",
    siteLink: "https://galeria-de-fotos-cyan.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Galeria-de-Fotos.git",
    },
    {
    title: "Ebac Motors",
    imgSrc: "/img/project/carro.png",
    alt: "Carro",
    tags: "#JS",
    siteLink: "https://ebac-motors-six-alpha.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Ebac-Motors.git",
    },
    {
    title: "Anuncio de venda",
    imgSrc: "/img/project/994737.png",
    alt: "Carrinho de compras",
    tags: "#JS",
    siteLink: "https://anuncio-jquery.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/formulario-plugs-jquery.git",
    },
    {
    title: "Portal News",
    imgSrc: "/img/project/image.png",
    alt: "Jornal",
    tags: "#JS",
    siteLink: "https://portal-de-noticias-grid.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Ebac_News.git",
    },
    {
    title: "Agenda",
    imgSrc: "/img/project/pngwing.com.png",
    alt: "Logo telefone",
    tags: "#JS",
    siteLink: "https://projeto-agendaonline.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Projeto_Agenda.git",
    },
    {
    title: "Sistema de médias",
    imgSrc: "/img/project/calculadora.png",
    alt: "Calculadora",
    tags: "#JS",
    siteLink: "https://monique-projeto-calculadora-medias.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Projeto_Calculadora_Medias.git",
    },
    {
    title: "Lista de tarefas",
    imgSrc: "/img/project/form.png",
    alt: "formulário",
    tags: "#JS #Jquery",
    siteLink: "https://lista-de-tarefas-jquery-opal.vercel.app/",
    githubLink: "https://github.com/Monique-Duarte/Lista-de-tarefas_jquery.git",
    },
];